# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda9754c365cd8e813ade9aba5021ca1cd42f53b317e72819d4d65f58329a13c49b12aec086c756115c939edcc227b795631c7c262cc4faf4ff87557dc6bb7b0

test:
  secret_key_base: a73daa108b5a4703d6bbf71afe232d1d8b9c22e832efb1628eb98531555077370e0276c9bd6549b1762d9e4547436859d949d7e1b333e65b2843c652dbf7cb64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
